[build]
  command = "npm install && npm run build"  # Simplify to "npm install" if no build step is needed
  publish = "public"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"  # Use the latest LTS version if compatible

# Optional: Add redirects for cleaner URLs
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
