[build]
  command = "npm install && npm run build"
  publish = "public"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"  # Adjust to your Node.js version requirement
